In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3],[5, 2, 20]])
a

array([[ 1,  2,  3],
       [ 5,  2, 20]])

In [4]:
b = a[1 , :]
b

array([ 5,  2, 20])

In [13]:
f = np.random.randn(200,1)
f.shape
pos = 0 
neg = 0
for i in f:
    if i > 0:
        pos = pos + 1
    else:
        neg = neg + 1
f"pos: {pos}, neg: {neg}"

'pos: 91, neg: 109'

In [14]:
g = f[ f > 0 ]
print(g.shape)
for i in g:
    if i <= 0:
        print(i)

(91,)


In [7]:
x = np.zeros (50) + 0.5
x

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

In [8]:
y = 0.5 * np.ones([1, len(x)])
y

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]])

In [9]:
z = x + y
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.]])

In [10]:
a = np.linspace(1,200)
a

array([  1.        ,   5.06122449,   9.12244898,  13.18367347,
        17.24489796,  21.30612245,  25.36734694,  29.42857143,
        33.48979592,  37.55102041,  41.6122449 ,  45.67346939,
        49.73469388,  53.79591837,  57.85714286,  61.91836735,
        65.97959184,  70.04081633,  74.10204082,  78.16326531,
        82.2244898 ,  86.28571429,  90.34693878,  94.40816327,
        98.46938776, 102.53061224, 106.59183673, 110.65306122,
       114.71428571, 118.7755102 , 122.83673469, 126.89795918,
       130.95918367, 135.02040816, 139.08163265, 143.14285714,
       147.20408163, 151.26530612, 155.32653061, 159.3877551 ,
       163.44897959, 167.51020408, 171.57142857, 175.63265306,
       179.69387755, 183.75510204, 187.81632653, 191.87755102,
       195.93877551, 200.        ])

In [11]:
b = a[: :-1]

array([200.        , 195.93877551, 191.87755102, 187.81632653,
       183.75510204, 179.69387755, 175.63265306, 171.57142857,
       167.51020408, 163.44897959, 159.3877551 , 155.32653061,
       151.26530612, 147.20408163, 143.14285714, 139.08163265,
       135.02040816, 130.95918367, 126.89795918, 122.83673469,
       118.7755102 , 114.71428571, 110.65306122, 106.59183673,
       102.53061224,  98.46938776,  94.40816327,  90.34693878,
        86.28571429,  82.2244898 ,  78.16326531,  74.10204082,
        70.04081633,  65.97959184,  61.91836735,  57.85714286,
        53.79591837,  49.73469388,  45.67346939,  41.6122449 ,
        37.55102041,  33.48979592,  29.42857143,  25.36734694,
        21.30612245,  17.24489796,  13.18367347,   9.12244898,
         5.06122449,   1.        ])

In [12]:
b[b <35]=0
b

array([200.        , 195.93877551, 191.87755102, 187.81632653,
       183.75510204, 179.69387755, 175.63265306, 171.57142857,
       167.51020408, 163.44897959, 159.3877551 , 155.32653061,
       151.26530612, 147.20408163, 143.14285714, 139.08163265,
       135.02040816, 130.95918367, 126.89795918, 122.83673469,
       118.7755102 , 114.71428571, 110.65306122, 106.59183673,
       102.53061224,  98.46938776,  94.40816327,  90.34693878,
        86.28571429,  82.2244898 ,  78.16326531,  74.10204082,
        70.04081633,  65.97959184,  61.91836735,  57.85714286,
        53.79591837,  49.73469388,  45.67346939,  41.6122449 ,
        37.55102041,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ])